services:
  workout_postgres:
    environment:
      POSTGRES_USER: pgWorkout
      POSTGRES_PASSWORD: jhhjhjghgdgfghkjgfghjkkhgfhjkljhgfghjkljhgfhjklelbgajhvapirgulökhabrgönNAEÖVBJN123
  workout_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: workout_frontend
    ports:
      - "8080:8080"
    networks:
      - workout_network

  workout_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: workout_backend
    ports:
      - "9876:9876"
    depends_on:
      - pgadmin
      - workout_postgres
    environment:
      - spring.datasource.url=jdbc:postgresql://workout_postgres:5432/pgWorkout
      - DB_PASSWORD=jhhjhjghgdgfghkjgfghjkkhgfhjkljhgfghjkljhgfhjklelbgajhvapirgulökhabrgönNAEÖVBJN123
      - DB_USER=pgWorkout
    networks:
      - workout_network