version: "3"
services:
  workout-postgres:
    container_name: workout-postgres
    image: postgres
    environment:
      POSTGRES_USER: pgWorkout
      POSTGRES_PASSWORD: jhhjhjghgdgfghkjgfghjkkhgfhjkljhgfghjkljhgfhjklelbgajhvapirgulökhabrgönNAEÖVBJN123
      POSTGRES_DB: pgWorkout
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - workout-network
    restart: always

  workout-frontend:
    image: mimasala/workout-frontend:main
    container_name: workout-frontend
    ports:
      - "8080:8080"
    networks:
      - workout-network

  workout-backend:
    image: mimasala/workout-backend:main
    container_name: workout-backend
    ports:
      - "9876:9876"
    depends_on:
      - pgadmin
      - workout-postgres
    environment:
      - spring.datasource.url=jdbc:postgresql://workout-postgres:5432/pgWorkout
      - DB_PASSWORD=jhhjhjghgdgfghkjgfghjkkhgfhjkljhgfghjkljhgfhjklelbgajhvapirgulökhabrgönNAEÖVBJN123
      - DB_USER=pgWorkout
    networks:
      - workout-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - workout-network
    restart: always

networks:
  workout-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
