services:
  workout_postgres:
    environment:
      POSTGRES_USER: pgWorkout
      POSTGRES_PASSWORD: jhhjhjghgdgfghkjgfghjkkhgfhjkljhgfghjkljhgfhjklelbgajhvapirgulökhabrgönNAEÖVBJN123
  workout_frontend:
    image: node:alpine
    container_name: workout_frontend
    entrypoint: /bin/sh
    ports:
      - "8000:8000"
    working_dir: /srv/app
    volumes:
      - ./frontend:/srv/app
    tty: true

  workout_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: workout_backend
    ports:
      - "8080:8080"
    depends_on:
      - pgadmin
      - workout_postgres
    environment:
      - spring.datasource.url=jdbc:postgresql://workout_postgres:5432/pgWorkout
    networks:
      - postgres