version: "3"

services:
  workout-postgres:
    container_name: workout_postgres
    image: postgres
    environment:
      POSTGRES-USER: pgWorkout
      POSTGRES_PASSWORD: jhhjhjghgdgfghkjgfghjkkhgfhjkljhgfghjkljhgfhjklelbgajhvapirgulökhabrgönNAEÖVBJN123
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  workout-frontend:
    image: mimasala/workout-frontend:main
    container_name: workout-frontend
    ports:
      - "8080:8080"

  workout-backend:
    image: mimasala/workout-backend:main
    container_name: workout-backend
    ports:
      - "9876:9876"
    depends_on:
      - workout-postgres
    environment:
      - spring.datasource.url=jdbc:postgresql://workout-postgres:5432/pgWorkout
      - DB_PASSWORD=jhhjhjghgdgfghkjgfghjkkhgfhjkljhgfghjkljhgfhjklelbgajhvapirgulökhabrgönNAEÖVBJN123
      - DB_USER=pgWorkout


volumes:
  postgres:
