version: "3"
services:
  workout-postgres:
    environment:
      POSTGRES_USER: pgWorkout
      POSTGRES_PASSWORD: jhhjhjghgdgfghkjgfghjkkhgfhjkljhgfghjkljhgfhjklelbgajhvapirgulökhabrgönNAEÖVBJN123
  workout-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: workout-frontend
    ports:
      - "8080:8080"
    networks:
      - workout-network

  workout-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: workout-backend
    ports:
      - "9876:9876"
    depends_on:
      - pgadmin
      - workout-postgres
    environment:
      - spring.datasource.url=jdbc:postgresql://workout-postgres:5432/pgWorkout
      - DB_PASSWORD=jhhjhjghgdgfghkjgfghjkkhgfhjkljhgfghjkljhgfhjklelbgajhvapirgulökhabrgönNAEÖVBJN123
      - DB_USER=pgWorkout
    networks:
      - workout-network